version: 2

artifacts:
  - name: main
    build:
      type: tier4/universe/main/amd64/v1

simulations:
  - name: log_sim_v2
    type: log_sim_v2
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: simulator/standard1/amd64/medium
        cpu: 8
        memory: 16384

release:
  components:
    - name: planning
      deployment:
        type: container
        artifact: main
    - name: perception
      deployment:
        type: container
        artifact: main
